import json

with open('untranslated.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

replacements = {
    '欢迎使用 FluentYTDL Pro。': 'Welcome to FluentYTDL Pro.',
    '本向导将协助您快速熟悉系统的基础工作流、模块分布与核心特性。': 'This wizard will help you quickly get familiar with the basic workflow, modules, and core features of the system.',
    '👉 快捷工作流（推荐）': '👉 Quick Workflow (Recommended)',
    '您可以在 <strong>设置 → 自动化</strong> 中开启「剪贴板自动识别」。': 'You can enable "Clipboard Auto Detect" in <strong>Settings → Automation</strong>.',
    '开启后，系统在后台监测到支持的媒体链接（包含单视频、播放列表或频道）时，将自动唤醒解析窗口，点击下载即可建立任务。': 'Once enabled, when the system detects supported media links in the background, it automatically wakes up the parsing window. Just click download to create a task.',
    '✍️ 标准解析工作流': '✍️ Standard Parsing Workflow',
    '1. 复制媒体链接并在主页搜索栏进行粘贴。<br>': '1. Copy the media link and paste it into the search bar on the home page.<br>',
    '2. 按下回车键或点击右侧解析按钮启动引擎。<br>': '2. Press Enter or click the parse button on the right to start the engine.<br>',
    '3. 系统将展现可用画质与音轨，按需选择并确认下载。': '3. The system will display available video qualities and audio tracks. Select as needed and confirm download.',
    '✅ 提示：核心解析与合并管线（yt-dlp、FFmpeg）已在系统内预置，无需额外配置环境。': '✅ Tip: Core parsing and merging pipelines (yt-dlp, FFmpeg) are pre-installed in the system, no extra environment setup is required.',
    '当需要下载具备年龄限制、会员专属的视频，或遭遇服务端机器人检测拦截时，系统需要身份凭证支持。': 'When downloading age-restricted, members-only videos, or encountering server bot detection blocks, the system requires identity credentials.',
    '身份验证接入方案': 'Authentication Access Solutions',
    '接入方式': 'Access Method',
    '推荐等级': 'Recommendation',
    '说明': 'Description',
    'WebView2 登录': 'WebView2 Login',
    '通过隔离的安全沙盒环境授权账号，稳定性最高，为官方推荐首选。': 'Authorize account through an isolated secure sandbox environment. Highest stability, official recommended choice.',
    '本机浏览器提取': 'Local Browser Extraction',
    '通过接口自动提取 Firefox 等浏览器的凭证，部分浏览器因安全策略受限。': 'Automatically extract credentials from browsers like Firefox via API. Some browsers restricted due to security policies.',
    '外部文件导入': 'External File Import',
    '通过浏览器扩展导出标准的 Netscape 格式文件，并在系统内导入。': 'Export standard Netscape format files via browser extension and import into the system.',
    '🛡️ 隐私合规：系统仅保留维持下载会话所需的验证令牌，自动过滤其他追踪性数据。': '🛡️ Privacy Compliance: The system only retains authentication tokens needed to maintain the download session, automatically filtering out other tracking data.',
    '系统核心特性': 'System Core Features',
    '🛡️ 质量风控引擎 (Quality Guard)': '🛡️ Quality Guard Engine',
    '前置与后置双重质量校验，拦截分辨率异常降级，保障下载质量。': 'Dual pre- and post-quality checks intercept abnormal resolution downgrades to ensure download quality.',
    '🔊 智能音轨打分机制': '🔊 Smart Audio Scoring Mechanism',
    '依据语言学分析评分，优先为您匹配高质量原生音轨或真人配音。': 'Scores based on linguistic analysis, prioritizing high-quality original or human-dubbed tracks for you.',
    '⚡ 频道与列表极速解析': '⚡ Ultra-fast Channel & Playlist Parsing',
    '构建三层优先调度系统，支持大规模播放列表的视口感知与懒加载。': 'Builds a three-tier priority scheduling system supporting viewport awareness and lazy loading for massive playlists.',
    '🎵 智能片段跳过 (SponsorBlock)': '🎵 Smart Segment Skipping (SponsorBlock)',
    '接入众包数据库，在处理管线中自动识别并跳过赞助商与推广片段。': 'Connects to a crowdsourced database to automatically identify and skip sponsorships and promotions in the processing pipeline.',
    '🥽 VR 空间后处理管道': '🥽 VR Spatial Post-processing Pipeline',
    '自动对 VR180/360 视频进行投影转换并注入空间元数据。': 'Automatically converts projections and injects spatial metadata for VR180/360 videos.',
    '🔄 任务状态持久化': '🔄 Task State Persistence',
    '底层基于 SQLite 管理任务生命周期，支持崩溃或意外重启后无缝恢复。': 'Manages task lifecycles using SQLite at the base level, supporting seamless recovery after crashes or unexpected restarts.',
    '侧边栏功能导航': 'Sidebar Navigation',
    '🏠 主页 / 基础解析': '🏠 Home / Basic Parsing',
    '核心工作区。粘贴链接即可解析单个视频或整个播放列表，并自由组装画质与音轨。': 'Core workspace. Paste a link to parse a single video or entire playlist, and freely assemble quality and audio tracks.',
    '📺 频道下载': '📺 Channel Download',
    '专为频道级别搬运设计。支持动态懒加载频道内的所有视频，并一键批量建立任务。': 'Designed specifically for channel-level archiving. Supports dynamic lazy loading of all videos in a channel and one-click bulk task creation.',
    '🥽 VR 下载': '🥽 VR Download',
    '独立的 VR 处理管线。自动提取 VR 全景格式并重投影，适配主流头显。': 'Independent VR processing pipeline. Automatically extracts VR panoramic formats and re-projects them for mainstream headsets.',
    '📝 物料提取 (字幕/封面)': '📝 Material Extraction (Subtitles/Covers)',
    '提供独立的提取页面，无需下载巨大视频本体即可高速获取多语种字幕与高清海报。': 'Provides an independent extraction page. Quickly get multi-language subtitles and HD posters without downloading huge video files.',
    '⬇️ 任务列表': '⬇️ Task List',
    '统一的下载调度中心。支持任务的全局暂停、开始，以及任务队列的批量管理。': 'Unified download scheduling center. Supports global pause, start, and batch management of the task queue.',
    '⚙️ 设置中心': '⚙️ Settings Center',
    '提供身份验证 (Cookie) 授权、底层组件维护、并发数调整及其他核心偏好设定。': 'Provides authentication (Cookie) authorization, underlying component maintenance, concurrency adjustment, and other core preferences.',
    '一切准备就绪': 'All Set',
    '核心服务进程已初始化，您可以开始建立下载任务了。': 'Core service processes have been initialized. You can now start creating download tasks.',
    '⚠️ 核心组件更新预警': '⚠️ Core Component Update Warning',
    '流媒体平台的防护策略更新极为频繁。如果您在未来使用中遭遇<strong>大面积解析错误、HTTP 403 异常或频繁的机器人验证拦截</strong>，这通常是因为上游策略发生了改变。': 'Streaming platform protection strategies are updated very frequently. If you encounter <strong>large-scale parsing errors, HTTP 403 exceptions, or frequent bot verification blocks</strong> in the future, it is usually because upstream strategies have changed.',
    '👉 <strong>排障第一步：</strong>请立即前往 <strong>「设置 → 更新」</strong> 页面，将内部核心组件升级至最新版本，99% 的解析问题都能由此解决。': '👉 <strong>Troubleshooting Step 1:</strong> Please immediately go to the <strong>"Settings → Updates"</strong> page and upgrade internal core components to the latest version. 99% of parsing issues can be resolved this way.',
    '基本操作': 'Basic Operation',
    '复制任意 YouTube 链接，在主页按 <code>Ctrl+V</code> 或点击粘贴按钮，按回车即可开始解析。': 'Copy any YouTube link, press <code>Ctrl+V</code> or click the paste button on the home page, and hit Enter to start parsing.',
    '支持的链接类型': 'Supported Link Types',
    '类型': 'Type',
    '示例': 'Example',
    '单个视频': 'Single Video',
    '播放列表': 'Playlist',
    '频道主页': 'Channel Home',
    '短视频': 'Shorts',
    '💡 <strong>提示：</strong>支持 B 站、Patreon 等数百个网站（底层引擎 yt-dlp 支持），但 FluentYTDL 的 UI 优化专为 YouTube 定制。': '💡 <strong>Tip:</strong> Hundreds of sites like Bilibili, Patreon are supported (via yt-dlp), but FluentYTDL UI is optimized for YouTube.',
    '自动模式（默认）': 'Auto Mode (Default)',
    '软件默认智能选择最佳画质，优先下载 1080p/4K 高清格式。大多数场景无需手动干预。': 'The software intelligently selects the best quality by default, prioritizing 1080p/4K HD formats. No manual intervention is needed.',
    'A+B 专业模式': 'A+B Pro Mode',
    '解析完成后点击「选择格式」按钮，可自由组合视频流和音频流：': 'After parsing, click the "Select Format" button to freely combine video and audio streams:',
    '<strong>视频流</strong>：选择画面分辨率（如 4K、1080p）和编码（H.264、VP9、AV1）': '<strong>Video Stream</strong>: Select resolution (e.g. 4K, 1080p) and codec (H.264, VP9, AV1)',
    '<strong>音频流</strong>：选择音质（如 Hi-Res Opus 256kbps、AAC 128kbps）': '<strong>Audio Stream</strong>: Select audio quality (e.g. Hi-Res Opus 256kbps, AAC 128kbps)',
    '例如：4K VP9 视频 + Hi-Res Opus 音频 = 最佳画质+音质的完美文件。': 'For example: 4K VP9 Video + Hi-Res Opus Audio = Perfect file with best visual + audio quality.',
    '为什么最高只有 1080p？': 'Why is it maxed out at 1080p?',
    '视频刚发布，4K/8K 编码需数小时，稍后重试': 'Video just released; 4K/8K encoding takes hours. Try again later.',
    '风控降级：需导入 Cookie + 换干净 IP': 'Risk control downgrade: Need to import Cookie + use clean IP.',
    '缺少 Deno JS 运行时：前往「设置 → 核心组件」检查安装': 'Missing Deno JS runtime: Go to "Settings → Core Components" to check installation.',
    'yt-dlp 过期：更新组件': 'yt-dlp outdated: Update components.',
    '开启方式': 'How to Enable',
    '进入 <strong>设置 → 自动化</strong>，开启「剪贴板自动识别」开关。': 'Go to <strong>Settings → Automation</strong> and turn on the "Clipboard Auto Detect" switch.',
    '使用效果': 'How it Works',
    '开启后，软件在后台监听剪贴板。只要复制了 YouTube 链接，就会自动弹出下载确认窗口，无需手动粘贴。点击「下载」即开始。': 'Once enabled, the software listens to the clipboard in the background. Whenever you copy a YouTube link, a download confirmation window pops up automatically.',
    '💡 <strong>推荐：</strong>这是最高效的使用方式，尤其适合日常频繁下载的用户。': '💡 <strong>Recommended:</strong> This is the most efficient way to use the app, especially for users who download frequently.',
    '批量操作': 'Batch Operation',
    '在下载列表中，使用工具栏上的「批量选择」按钮，可一次性暂停、恢复或删除多个任务。': 'In the task list, use the "Batch Select" button to pause, resume, or delete multiple tasks at once.',
    '播放列表全局格式预设': 'Playlist Global Format Presets',
    '解析播放列表后，使用工具栏的「格式设置」按钮统一配置所有视频的分辨率和格式，无需逐个设置。': 'After parsing a playlist, use the "Format Settings" button to unify resolutions and formats for all videos.',
    '并发控制建议': 'Concurrency Control Advice',
    '场景': 'Scenario',
    '建议': 'Advice',
    '日常下载': 'Daily Download',
    '保持默认并发任务数': 'Keep default concurrent tasks',
    '大播放列表（500+）': 'Large Playlists (500+)',
    '分批解析，避免触发风控': 'Parse in batches to avoid triggering risk controls',
    '网络不稳定': 'Unstable Network',
    '降低并发分片数': 'Reduce concurrent fragments',
    '三种获取方式对比': 'Comparison of the Three Methods',
    '方式': 'Method',
    '推荐度': 'Recommendation',
    '强烈推荐': 'Highly Recommended',
    '弹出安全沙盒窗口登录，一键获取，无兼容性问题': 'Login via isolated sandbox popup. 1-click fetch, no compatibility issues.',
    'Firefox 自动提取': 'Firefox Auto-Extract',
    '推荐': 'Recommended',
    '无需管理员权限，稳定可靠': 'No admin privileges needed, stable and reliable.',
    '手动导入': 'Manual Import',
    '兜底方案': 'Fallback Method',
    '用扩展导出 cookies.txt 后导入，需定期更新': 'Export cookies.txt via extension and import. Requires regular updates.',
    'WebView2 登录获取流程': 'WebView2 Login Workflow',
    '在设置页点击「WebView2 登录获取」，弹出独立的 WebView2 沙盒窗口': 'Click "WebView2 Login Fetch" to open an isolated sandbox window.',
    '在沙盒中正常登录 Google/YouTube 账号': 'Log into your Google/YouTube account normally in the sandbox.',
    '软件自动检测登录状态，采集 Cookie 并清洗': 'The software automatically detects login state, collects, and cleans the Cookie.',
    'Cookie 自动同步到 yt-dlp，完成': 'Cookie is auto-synced to yt-dlp, done!',
    '浏览器兼容性': 'Browser Compatibility',
    '浏览器': 'Browser',
    '自动提取': 'Auto Extract',
    'Firefox': 'Firefox',
    '稳定可用': 'Stable',
    '无需管理员权限，推荐首选': 'No admin rights needed. Recommended choice.',
    'Edge': 'Edge',
    '需管理员权限': 'Admin Required',
    'App-Bound Encryption 限制': 'App-Bound Encryption limitations.',
    'Chrome': 'Chrome',
    '基本不可用': 'Mostly Unusable',
    'v127+ 加密机制导致第三方无法解密': 'v127+ encryption mechanism prevents third-party decryption.',
    '💡 <strong>重要：</strong>Chrome 自动提取极不稳定。如果你使用 Chrome 且频繁失败，请切换到 WebView2 或 Firefox。': '💡 <strong>Important:</strong> Chrome auto-extraction is extremely unstable. If you use Chrome and fail frequently, switch to WebView2 or Firefox.',
    '什么是 PO Token？': 'What is a PO Token?',
    '<strong>PO Token（Proof of Origin Token）</strong>是 YouTube 用于验证请求来源合法性的数字令牌，向 YouTube 证明self.tr("这个请求来自真实客户端")。': '<strong>PO Token</strong> is a digital token used by YouTube to verify request origins.',
    '没有 PO Token 时可能遇到': 'Symptoms of missing PO Token',
    '触发 "Sign in to confirm you\'re not a bot" 人机验证': 'Triggers "Sign in to confirm you\'re not a bot" verification.',
    '高画质格式被隐藏（仅返回 720p 或更低）': 'High quality formats are hidden (returns only 720p or lower).',
    '直接返回 HTTP 403 拒绝访问': 'Directly returns HTTP 403 Forbidden.',
    'PO Token 与 Cookie 的关系': 'PO Token vs Cookie',
    'PO Token': 'PO Token',
    'Cookie': 'Cookie',
    '证明什么': 'Proves What',
    '请求来自合法客户端': 'Request is from a legit client',
    '用户身份和登录状态': 'User identity and login state',
    '解决什么': 'Solves What',
    '机器人检测、基础格式访问': 'Bot detection, basic format access',
    '年龄限制、会员内容、高码率流': 'Age-restrictions, members-only, high bitrate streams',
    '缺失后果': 'Missing Consequence',
    '触发人机验证、画质受限': 'Bot verification, restricted quality',
    '无法下载受限内容': 'Unable to download restricted content',
    '💡 <strong>最佳实践：</strong>两者同时启用是最稳定的配置。PO Token 确保请求不被拦截，Cookie 确保有权限获取完整内容。': '💡 <strong>Best Practice:</strong> Enabling both is the most stable configuration.',
    'POT Provider 预热': 'POT Provider Warmup',
    '应用启动时，POT Provider 需要 5-15 秒初始化 BotGuard 环境。预热期间日志显示「正在初始化」，完成后显示「已激活」。如果一直无法激活，请检查 Deno 是否已安装。': 'At app startup, POT Provider requires 5-15 seconds to initialize the BotGuard environment.',
    '默认行为': 'Default Behavior',
    'FluentYTDL 默认「跟随系统代理」。只要系统或代理软件开启了系统代理，软件即可自动使用。': 'FluentYTDL defaults to "Follow System Proxy".',
    '代理软件配置': 'Proxy Software Config',
    '软件': 'Software',
    '操作': 'Action',
    'V2RayN': 'V2RayN',
    '底部切换为「系统代理」，或开启 TUN': 'Set bottom bar to "System Proxy", or turn on TUN.',
    'Clash Verge / CFW': 'Clash Verge / CFW',
    '启用「System Proxy」开关，不行就开 TUN': 'Enable "System Proxy" switch, or turn on TUN.',
    '其他': 'Other',
    '确保开启self.tr("系统代理")/self.tr("全局模式")，非仅self.tr("规则/PAC 模式")': 'Ensure "System Proxy" / "Global Mode" is enabled.',
    '手动配置代理': 'Manual Proxy Config',
    '如果自动代理不工作，在 <strong>设置 → 网络连接</strong> 中选择「手动配置」，填入代理端口（如 <code>http://127.0.0.1:7890</code>）。': 'If auto-proxy fails, go to <strong>Settings → Network Connection</strong>, select "Manual Config".',
    '💡 <strong>注意：</strong>不推荐长期使用手动代理。代理软件换端口后需手动同步修改，容易遗漏。': '💡 <strong>Note:</strong> Long-term manual proxy isn\'t recommended.',
    'DNS 错误 / 连接重置': 'DNS Errors / Connection Resets',
    '<strong>端口未对齐</strong>：检查设置中的端口号是否与代理软件一致': '<strong>Port Mismatch</strong>: Check if the port in settings matches your proxy software.',
    '<strong>节点被封锁</strong>：更换其他国家/地区的节点': '<strong>Blocked Node</strong>: Switch to a node in a different country/region.',
    '<strong>TUN 模式</strong>：开启后软件直接接管系统网络流量，无需配置端口': '<strong>TUN Mode</strong>: When enabled, the software intercepts all system traffic.',
    '遇到 "Sign in to confirm you\'re not a bot"': 'When facing "Sign in to confirm you\'re not a bot"',
    '按优先级依次尝试：': 'Try in order of priority:',
    '<strong>点击应用弹出的自动修复引导</strong> — 自动诊断根因并一键处理': '<strong>Click Auto-Fix Wizard</strong> — Auto-diagnoses root cause and fixes in 1-click.',
    '<strong>更新 yt-dlp</strong> — 前往「设置 → 核心组件」一键更新（最有效）': '<strong>Update yt-dlp</strong> — Go to "Settings → Core Components" (most effective).',
    '<strong>刷新 Cookie</strong> — 推荐 WebView2 重新登录，或切换到 Firefox 提取': '<strong>Refresh Cookie</strong> — Recommend re-logging via WebView2.',
    '<strong>更换代理节点</strong> — 当前 IP 可能已被标记': '<strong>Change Proxy Node</strong> — Current IP might be flagged.',
    '需要登录/权限不足': 'Login Required / Insufficient Permissions',
    '以下场景需要导入 Cookie：': 'Cookie import is required for:',
    '年龄限制（18禁）内容': 'Age-restricted (18+) content.',
    '频道会员专属内容': 'Channel members-only content.',
    '受强力风控保护的极高码率流': 'Ultra-high bitrate streams protected by strong risk controls.',
    '私享视频': 'Private videos.',
    '💡 <strong>提示：</strong>绝大多数公开视频不需要登录。日常使用直接复制链接粘贴解析即可。': '💡 <strong>Tip:</strong> The vast majority of public videos do not require login.',
    '修改账号资料后出现验证错误': 'Verification Errors after Profile Update',
    '修改用户名/头像触发了 Google 安全风控。解决：浏览器退出 YouTube → 重新登录 → 播放一个视频确认正常 → 重新获取 Cookie。': 'Changing usernames triggers Google security checks. Fix: Logout → Relogin → Fetch Cookie.',
    '工作原理': 'How it Works',
    'SponsorBlock 社区维护了一个众包标注数据库，记录了数百万视频中的赞助广告时间段。yt-dlp 下载时自动查询并处理。': 'The SponsorBlock community maintains a database mapping sponsor segments.',
    '支持的类别': 'Supported Categories',
    '类别': 'Category',
    'sponsor': 'sponsor',
    '赞助广告': 'Sponsorship adverts',
    'selfpromo': 'selfpromo',
    '频道自我推广': 'Channel self-promotions',
    'interaction': 'interaction',
    '订阅提醒、点赞提醒等': 'Subscribe/like reminders',
    '处理方式': 'Action Types',
    '<strong>Remove（移除）</strong>：使用 FFmpeg 自动裁剪掉广告片段': '<strong>Remove</strong>: Uses FFmpeg to automatically crop out ad segments.',
    '<strong>Mark（标记）</strong>：将广告段标记为章节，播放时可跳过': '<strong>Mark</strong>: Marks ad segments as chapters.',
    '在 <strong>设置 → 下载选项 → SponsorBlock</strong> 中启用并选择类别和处理方式。': 'Enable and configure in <strong>Settings → Download Options → SponsorBlock</strong>.',
    '自动检测机制': 'Auto Detect Mechanism',
    'FluentYTDL 解析视频时自动检测 VR 内容（关键词、格式元数据、分辨率异常），检测到后自动使用 <code>android_vr</code> 客户端获取 VR 专属高分辨率格式（最高 8K）。': 'FluentYTDL auto-detects VR content and uses the android_vr client to fetch formats.',
    '三种投影类型': 'Three Projection Types',
    '投影类型': 'Projection Type',
    '画面特征': 'Visual Charasteristics',
    'Equirectangular': 'Equirectangular',
    '最常见的 360 格式': 'Most common 360 format',
    '宽高比 2:1，上下拉伸': '2:1 aspect ratio, stretched top/bottom',
    'Mesh': 'Mesh',
    'VR180 常用': 'Common in VR180',
    '圆形鱼眼画面': 'Circular fisheye visuals',
    'EAC': 'EAC',
    'YouTube 自研高效率格式': 'YouTube proprietary efficient format',
    '六面展开图': 'Unfolded cube map (six faces)',
    '播放说明': 'Playback Instructions',
    'VR 视频在普通播放器中呈畸变是正常的，需用 VR 头显或全景播放器（Skybox、PotPlayer 全景模式）。': 'It\'s normal for VR videos to appear distorted in standard players. Use a VR headset.',
    '💡 <strong>注意：</strong>EAC 格式的 8K 转码极度消耗资源（建议 32GB+ 内存），没有高性能硬件时建议限制在 4K/6K。': '💡 <strong>Note:</strong> 8K transcoding of EAC formats consumes extreme resources.',
    '三个核心概念': 'Three Core Concepts',
    '视频文件 = <strong>容器</strong>（MP4/MKV/WebM）+ <strong>视频编码</strong>（H.264/VP9/AV1）+ <strong>音频编码</strong>（AAC/Opus）': 'Video File = <strong>Container</strong> + <strong>Video Codec</strong> + <strong>Audio Codec</strong>',
    '视频编码对比': 'Video Codec Comparison',
    '编码': 'Codec',
    '特点': 'Features',
    '兼容性': 'Compatibility',
    'H.264 (AVC)': 'H.264 (AVC)',
    '最老牌，兼容性最强': 'Oldest, highest compatibility',
    '全平台通吃': 'Works on all platforms',
    'VP9': 'VP9',
    'YouTube 高画质流主力': 'Mainstream for YouTube HD',
    'PC/手机可以，部分电视不行': 'Good on PC/Phones, some TVs struggle',
    'AV1': 'AV1',
    '压缩效率最高': 'Highest compression efficiency',
    '新设备支持，老设备大多不行': 'New devices support it, old devices usually don\'t',
    '容器格式对比': 'Container Format Comparison',
    '容器': 'Container',
    '支持编码': 'Supported Codecs',
    '字幕': 'Subtitles',
    '多音轨': 'Multi-Track',
    'MP4': 'MP4',
    'H.264+AAC 完美 / VP9 受限 / Opus 不支持': 'H.264+AAC perfect / VP9 limited',
    '单轨': 'Single track',
    '有限': 'Limited',
    'MKV': 'MKV',
    '几乎所有编码': 'Almost all codecs',
    '完整多轨': 'Full multi-track',
    '完整支持': 'Full support',
    'WebM': 'WebM',
    'VP9/AV1+Opus': 'VP9/AV1+Opus',
    '不支持 SRT/ASS': 'No SRT/ASS support',
    'FluentYTDL 智能容器决策': 'FluentYTDL Smart Container Decision',
    '多音轨/多语言字幕嵌入 → 自动升级为 MKV': 'Multi-track audio/subtitles embedded → Auto-upgrades to MKV',
    'MP4 + m4a 音频 → MP4（无损 remux）': 'MP4 + m4a audio → MP4 (Lossless remux)',
    '其他混合编码 → MKV（万能容器）': 'Other mixed codecs → MKV (Universal container)',
    '💡 <strong>什么是 remux？</strong>重封装是把音视频数据从一个容器搬到另一个容器，不重新编码，速度极快且画质零损失。': '💡 <strong>What is remux?</strong> Repackaging audio/video without re-encoding.',
    '任务持久化': 'Task Persistence',
    'FluentYTDL 使用 SQLite 数据库（WAL 模式）存储所有下载任务。任务的每个状态变化（加入队列、开始、进度、完成、错误）都会实时写入数据库。': 'FluentYTDL uses an SQLite database (WAL mode) to store all download tasks.',
    '崩溃恢复': 'Crash Recovery',
    '如果在下载过程中关闭程序（甚至意外断电/崩溃），重启后任务列表依然完整保留。': 'If the program closes during download, the task list remains completely preserved.',
    '降级策略': 'Downgrade Strategy',
    '重启前处于「运行中」或「解析中」的任务，会自动降级为「暂停」状态，可手动恢复': 'Tasks that were "Running" automatically downgrade to "Paused" status.',
    '纯提取任务（封面/字幕）重启后标记为错误，避免产生「幽灵任务」': 'Pure extraction tasks (Cover/Subtitle) are marked as errors upon restart.',
    '💡 <strong>提示：</strong>这意味着您可以放心地在下载过程中关闭软件，下次打开时任务不会丢失。': '💡 <strong>Tip:</strong> You can safely close the software during a download.',
    '核心组件一览': 'Core Components Overview',
    '组件': 'Component',
    '用途': 'Purpose',
    'yt-dlp': 'yt-dlp',
    '核心下载引擎，解析链接、获取流媒体数据': 'Core download engine. Parses links, fetches streaming media data.',
    'FFmpeg': 'FFmpeg',
    '合并音视频轨、转码封装、嵌入封面与字幕': 'Merges audio/video tracks, transcodes/repackages, embeds covers and subtitles.',
    'Deno': 'Deno',
    'JS 运行时，解析 YouTube 加密签名，缺失时丢失大量格式': 'JS runtime. Parses YouTube\'s encrypted signatures.',
    'POT Provider': 'POT Provider',
    '动态生成 PO Token，绕过机器人检测': 'Dynamically generates PO Tokens to bypass bot detection.',
    'AtomicParsley': 'AtomicParsley',
    '向 MP4/M4A 文件嵌入封面和元数据标签': 'Embeds covers and metadata tags into MP4/M4A files.',
    '管理方式': 'Management',
    '在 <strong>设置 → 核心组件</strong> 页面可查看安装状态、当前版本，并一键检查更新。所有组件首次启动时自动下载安装，开箱即用。': 'On the <strong>Settings → Core Components</strong> page, you can check installation status.',
    'yt-dlp 更新渠道': 'yt-dlp Update Channels',
    '渠道': 'Channel',
    '更新频率': 'Frequency',
    '稳定性': 'Stability',
    '适用场景': 'Use Case',
    'stable': 'stable',
    '数周一次': 'Every few weeks',
    '最稳定': 'Most stable',
    '日常使用（默认推荐）': 'Daily use (Default Recommended)',
    'nightly': 'nightly',
    '每日构建': 'Daily build',
    '较稳定': 'Relatively stable',
    'YouTube 改版后 stable 未修复时': 'When stable is unpatched after YouTube changes',
    'master': 'master',
    '每次代码合并': 'Per code merge',
    '可能不稳定': 'Potentially unstable',
    '开发测试': 'Development/testing',
    '紧急自救指南': 'Emergency Self-Rescue Guide',
    '当 YouTube 突然大规模改版导致所有下载失败时：': 'When YouTube makes massive layout changes causing all downloads to fail:',
    '首先尝试更新 <strong>stable</strong> 渠道 — 大部分情况下社区会快速修复': 'First try updating the <strong>stable</strong> channel.',
    '如果 stable 还没跟上，临时切换到 <strong>nightly</strong> — 包含最新的修复补丁': 'If stable hasn\'t caught up, temporarily switch to <strong>nightly</strong>.',
    '修复被合并到 stable 后再切回来': 'Switch back to stable once fixes are merged.',
    '镜像源配置': 'Mirror Source Configuration',
    '中国大陆用户在「设置 → 核心组件」中可切换为 ghproxy 镜像加速 GitHub 下载。组件更新也会使用「设置 → 网络连接」中配置的代理。': 'Users in mainland China can switch to the \'ghproxy\' mirror to accelerate GitHub downloads.',
    '并发分片数': 'Concurrent Fragment Count',
    '设置值': 'Value',
    '风险': 'Risk',
    '1-2': '1-2',
    '网络不稳定、代理带宽小': 'Unstable network, low proxy bandwidth',
    '无': 'None',
    '4（默认）': '4 (Default)',
    '大多数场景的最佳平衡': 'Best balance for most scenarios',
    '8-16': '8-16',
    '高带宽直连、极速下载': 'High bandwidth direct connection',
    '可能触发 429 限流': 'Might trigger 429 rate limits',
    '16+': '16+',
    '不推荐': 'Not recommended',
    '高概率限流、IP 封锁': 'High chance of rate limiting or IP block',
    '💡 <strong>注意：</strong>分片数并非越大越快。YouTube 会对单 IP 的并发连接数监控，超过阈值会触发限流甚至封锁。默认值 4 是最佳平衡点。': '💡 <strong>Note:</strong> Higher fragments don\'t mean faster. Exceeding thresholds triggers limits.',
    '下载限速': 'Download Rate Limit',
    '在「设置 → 下载选项」中可设置速率上限，适用场景：': 'Configure speed limits under "Settings → Download Options".',
    '避免下载占满全部带宽': 'Preventing downloads from eating up all your bandwidth.',
    '降低被风控检测的概率': 'Reducing the probability of triggering risk controls.',
    '后台长时间挂机下载': 'Long-term background downloads.',
    '错误代码速查表': 'Error Code Quick Reference',
    '关键词': 'Keyword',
    '错误类型': 'Error Type',
    '核心原因': 'Core Reason',
    '解决方案': 'Solution',
    'ffmpeg not found': 'ffmpeg not found',
    '组件缺失': 'Missing Component',
    '缺少 FFmpeg 无法合并音视频': 'Missing FFmpeg, cannot merge audio/video',
    '设置 → 核心组件 → 检查更新': 'Settings → Core Components → Check Updates',
    'HTTP Error 403': 'HTTP Error 403',
    '访问被拒': 'Access Denied',
    'IP 被 YouTube 风控': 'IP risk-flagged by YouTube',
    '更新 Cookie + 更换代理节点': 'Update Cookie + Change Proxy Node',
    'Sign in / private': 'Sign in / private',
    '需要登录或会员权限': 'Needs login or member rights',
    '导入有效 Cookie': 'Import valid Cookie',
    'timed out / 10060': 'timed out / 10060',
    '网络超时': 'Network Timeout',
    '无法连接 YouTube 服务器': 'Cannot connect to YouTube servers',
    '检查代理软件系统代理模式': 'Check Proxy Software System Proxy Mode',
    'Video unavailable': 'Video unavailable',
    '视频无效': 'Invalid Video',
    '视频被删或区域限制': 'Video deleted or region blocked',
    '确认链接在浏览器中可访问': 'Verify link is accessible in browser',
    'postprocessing': 'postprocessing',
    '后处理失败': 'Post-process Fail',
    '格式合成出错或磁盘满': 'Format merging error or disk full',
    '切换下载格式 (MKV/MP4)': 'Switch download format (MKV/MP4)',
    '403 Forbidden 深度解析': 'Deep Dive into 403 Forbidden',
    '这是最常见的问题。YouTube 会屏蔽「非浏览器」流量。解决步骤：': 'This is the most common issue. YouTube blocks "non-browser" traffic. Solutions:',
    '<strong>更新 Cookie</strong>（推荐）：使用 WebView2 登录或 Firefox 提取': '<strong>Update Cookie</strong> (Recommended): Relogin via WebView2.',
    '<strong>更换节点</strong>：「万人骑」公共节点容易被封锁，切换到冷门节点': '<strong>Change Node</strong>: Public nodes are easily blocked. Switch to an obscure one.',
    '<strong>更新 yt-dlp</strong>：社区会持续适配 YouTube 的反爬变化': '<strong>Update yt-dlp</strong>: The community continually adapts to YouTube\'s anti-scraping changes.',
    '💡 <strong>提示：</strong>403 的 IP 封锁通常需要等 12-24 小时解封。更换节点是最快的解决方案。': '💡 <strong>Tip:</strong> 403 IP bans usually lift after 12-24 hours. Changing nodes is the fastest fix.',
    '获取运行日志': 'Fetch Run Logs',
    '进入 <strong>设置页 → 系统 → 日志管理</strong>': 'Go to <strong>Settings → System → Log Management</strong>',
    '点击右侧文件夹图标打开日志目录': 'Click the folder icon on the right to open the log directory',
    '找到当天 <code>.log</code> 文件（如 <code>app_2026-04-23.log</code>）': 'Find today\'s <code>.log</code> file',
    '也可点击「查看日志」在应用内实时预览，支持级别过滤和关键词搜索。': 'You can also click "View Logs" for a real-time preview inside the app.',
    '一键上报 Bug': 'One-Click Bug Reporting',
    '遇到未知的解析异常或下载中断时，点击报错卡片处弹出的「反馈此错误」图标按钮，会自动预填错误信息提报给开发者。': 'Click the "Report this Error" icon button on the error card to auto-fill the error information.',
    '💡 <strong>提示：</strong>附上日志文件能让开发者更快定位问题。在 GitHub Issue 中粘贴日志内容即可。': '💡 <strong>Tip:</strong> Attaching log files helps developers locate issues much faster.'
}

for key, val in data.items():
    if not val:
        translated_val = key
        # Sort replacements by length descending to replace longer phrases first
        sorted_repls = sorted(replacements.items(), key=lambda x: len(x[0]), reverse=True)
        for src, dst in sorted_repls:
            translated_val = translated_val.replace(src, dst)
        data[key] = translated_val

with open('translated.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=4)
print('Done translating.')
